active: false
created_at: '2026-06-10T18:25:37.546884+00:00'
display_name: Nurse Humor Gifts
etsy_shop_id: ''
listing_count_target: 50
niche:
  primary: Funny medical profession gifts & merchandise
  secondary:
  - nurse gift
  - medical humor
  subreddits:
  - nursing
  - medicalschool
  target_audience: Nurses, doctors, medical students
product_types:
- mug
- sticker
- t-shirt
store_slug: nurse-humor-gifts
